version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app/backend
    entrypoint: uvicorn
    env_file:
      - .env
    command:
      ["backend.app:app", "--reload", "--host", "0.0.0.0", "--port", "8080"]
  database:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=nidus
    ports:
      - "3306:3306"
